services:
  web:
    build: .
    command: sh -c "ampalibe run --dev"
    ports:
      - 4555:4555
    volumes:
      - .:/app  # Monte le répertoire courant dans /app du conteneur
    env_file:
      - .env