version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - DB_HOST=34.28.32.137
      - DB_USER=root
      - DB_PASSWORD=07ke6u%56O5x
      - DB_NAME=vosaryai
    depends_on:
      - db
    command: ampalibe run

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_DATABASE=vosaryai
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
